# API-specific configuration
api:
  host: "0.0.0.0"        # Host address to bind the API
  port: 8000             # Port for the API
  debug: true            # Debug mode for development

# Database connection settings
database:
  host: "localhost"      # Database host
  port: 5432             # Database port
  name: "vitaledge_datalake"  # Database name
  user: "username"       # Database username
  password: "password"   # Database password

# Logging configuration
logging:
  level: "INFO"          # Logging level (DEBUG, INFO, WARN, ERROR)
  file: "logs/api.log"   # Log file path
